### ISSUE TITLE
ocean-menu-notification-counter CSS class missing styles

### ISSUE THREAD

**Issue by ztackett11** [oceanwp/ocean-extra#45]
The OceanWP admin button's notifications appears to be missing it's styles that creates the notification bubble in the admin bar. I created a custom fix for myself but it may still persist for others.

**Comment by MarkHollo** [comment]
hi @ztackett11 the problem in question is fixed with the latest Ocean Extra 2.0.6 version :)

If you continue to experience further problems or notice anything else, please feel free to start a new thread.

Thanks for using OceanWP and stay awesome!

Have a great day
