### ISSUE TITLE
Uncaught Error: Undefined constant "OCEANWP_CSS_DIR_URI"

### ISSUE THREAD

**Issue by Manucharyan** [oceanwp/ocean-extra#68]
**Fatal error: Uncaught Error: Undefined constant "OCEANWP_CSS_DIR_URI"** in /home/locean/public_html/wp-content/plugins/ocean-extra/includes/menu-icons/includes/library/icon-selector/includes/types/font.php:68 Stack trace: #0 /home/locean/public_html/wp-content/plugins/ocean-extra/includes/menu-icons/includes/library/icon-selector/includes/types/base.php(62): OE_Icon_Picker_Type_Font->get_stylesheet_uri() #1 /home/locean/public_html/wp-content/plugins/ocean-extra/includes/menu-icons/includes/library/icon-selector/includes/types/font.php(91): OE_Icon_Picker_Type->__get('stylesheet_uri') #2 /home/locean/public_html/wp-includes/class-wp-hook.php(308): OE_Icon_Picker_Type_Font->register_assets(Object(OE_Icon_Picker_Loader)) #3 /home/locean/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #4 /home/locean/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #5 /home/locean/public_html/wp-content/plugins/ocean-extra/includes/menu-icons/includes/library/icon-selector/includes/loader.php(78): do_action('oe_icon_picker_...', Object(OE_Icon_Picker_Loader)) #6 /home/locean/public_html/wp-content/plugins/ocean-extra/includes/menu-icons/includes/library/icon-selector/includes/loader.php(59): OE_Icon_Picker_Loader->__construct() #7 /home/locean/public_html/wp-content/plugins/ocean-extra/includes/menu-icons/includes/library/icon-selector/icon-selector.php(194): OE_Icon_Picker_Loader::instance() #8 /home/locean/public_html/wp-content/plugins/ocean-extra/includes/menu-icons/includes/library/icon-selector/icon-selector.php(127): OE_Icon_Selector->init_loader() #9 /home/locean/public_html/wp-includes/class-wp-hook.php(308): OE_Icon_Selector->init('') #10 /home/locean/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #11 /home/locean/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #12 /home/locean/public_html/wp-settings.php(645): do_action('wp_loaded') #13 /home/locean/public_html/wp-config.php(91): require_once('/home/locean/pu...') #14 /home/locean/public_html/wp-load.php(50): require_once('/home/locean/pu...') #15 /home/locean/public_html/wp-admin/admin.php(34): require_once('/home/locean/pu...') #16 /home/locean/public_html/wp-admin/plugins.php(10): require_once('/home/locean/pu...') #17 {main} thrown in /home/locean/public_html/wp-content/plugins/ocean-extra/includes/menu-icons/includes/library/icon-selector/includes/types/font.php on line 68

Please help me to fix the issue as the testing shown that only ocean extra plugin activated and gave an error.

**Comment by MarkHollo** [comment]
Hi @Manucharyan,

Thanks for taking the time to report this and thanks for the patience for receiving a reply here.

But as you already know we fixed the problem with 2.1.7 (current version 2.2.0) so that is what counted the most :)

If you experience any other problems, please feel free to start a new thread.

Thanks for using OceanWP 🥇
